name: todoapp
description: The application to plan a day
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_bloc: ^4.0.0
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

flutter:

  uses-material-design: true
